[package]
name = "references_and_borrowing"
version = "0.1.0"
authors = ["Alejandro Hartlöhner <hartformer@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
